// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wadatsumi.Jinja.Data;

namespace Wadatsumi.Migrations
{
    [DbContext(typeof(JinjaDbContext))]
    [Migration("20210504085335_AddTheory")]
    partial class AddTheory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Goshuin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JinjaID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("JinjaID");

                    b.ToTable("GoshuinDbSet");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Jinja", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kana")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocationID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RyouseikokuID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("LocationID");

                    b.HasIndex("RyouseikokuID");

                    b.ToTable("JinjaDbSet");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Kami", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("KamiDbSet");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int?>("MunicipalityID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PrefectureID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("MunicipalityID");

                    b.HasIndex("PrefectureID");

                    b.ToTable("LocationDbSet");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Municipality", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MuniCd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrefectureID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("PrefectureID");

                    b.ToTable("MunicipalityDbSet");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Prefecture", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("PrefectureDbSet");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Region", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("RegionDbSet");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Ryouseikoku", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RegionID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("RegionID");

                    b.ToTable("RyouseikokuDbSet");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Saijin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JinjaID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KamiID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("JinjaID");

                    b.HasIndex("KamiID");

                    b.ToTable("SaijinDbSet");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Shinmei", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KamiID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kana")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("KamiID");

                    b.ToTable("ShinmeiDbSet");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Theory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KamiID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("KamiID");

                    b.ToTable("TheoryDbSet");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.TheoryRelation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JinjaID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KamiID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TheoryID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("JinjaID");

                    b.HasIndex("KamiID");

                    b.HasIndex("TheoryID");

                    b.ToTable("TheoryRelationDbSet");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Goshuin", b =>
                {
                    b.HasOne("Wadatsumi.Jinja.Data.Jinja", "Jinja")
                        .WithMany()
                        .HasForeignKey("JinjaID");

                    b.Navigation("Jinja");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Jinja", b =>
                {
                    b.HasOne("Wadatsumi.Jinja.Data.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID");

                    b.HasOne("Wadatsumi.Jinja.Data.Ryouseikoku", "Ryouseikoku")
                        .WithMany()
                        .HasForeignKey("RyouseikokuID");

                    b.Navigation("Location");

                    b.Navigation("Ryouseikoku");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Location", b =>
                {
                    b.HasOne("Wadatsumi.Jinja.Data.Municipality", "Municipality")
                        .WithMany()
                        .HasForeignKey("MunicipalityID");

                    b.HasOne("Wadatsumi.Jinja.Data.Prefecture", "Prefecture")
                        .WithMany()
                        .HasForeignKey("PrefectureID");

                    b.Navigation("Municipality");

                    b.Navigation("Prefecture");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Municipality", b =>
                {
                    b.HasOne("Wadatsumi.Jinja.Data.Prefecture", "Prefecture")
                        .WithMany()
                        .HasForeignKey("PrefectureID");

                    b.Navigation("Prefecture");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Ryouseikoku", b =>
                {
                    b.HasOne("Wadatsumi.Jinja.Data.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionID");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Saijin", b =>
                {
                    b.HasOne("Wadatsumi.Jinja.Data.Jinja", "Jinja")
                        .WithMany("SaijinList")
                        .HasForeignKey("JinjaID");

                    b.HasOne("Wadatsumi.Jinja.Data.Kami", "Kami")
                        .WithMany()
                        .HasForeignKey("KamiID");

                    b.Navigation("Jinja");

                    b.Navigation("Kami");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Shinmei", b =>
                {
                    b.HasOne("Wadatsumi.Jinja.Data.Kami", "Kami")
                        .WithMany("ShinmeiList")
                        .HasForeignKey("KamiID");

                    b.Navigation("Kami");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Theory", b =>
                {
                    b.HasOne("Wadatsumi.Jinja.Data.Kami", null)
                        .WithMany("TheoryList")
                        .HasForeignKey("KamiID");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.TheoryRelation", b =>
                {
                    b.HasOne("Wadatsumi.Jinja.Data.Jinja", "Jinja")
                        .WithMany("TheoryList")
                        .HasForeignKey("JinjaID");

                    b.HasOne("Wadatsumi.Jinja.Data.Kami", "Kami")
                        .WithMany()
                        .HasForeignKey("KamiID");

                    b.HasOne("Wadatsumi.Jinja.Data.Theory", "Theory")
                        .WithMany("ReferenceList")
                        .HasForeignKey("TheoryID");

                    b.Navigation("Jinja");

                    b.Navigation("Kami");

                    b.Navigation("Theory");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Jinja", b =>
                {
                    b.Navigation("SaijinList");

                    b.Navigation("TheoryList");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Kami", b =>
                {
                    b.Navigation("ShinmeiList");

                    b.Navigation("TheoryList");
                });

            modelBuilder.Entity("Wadatsumi.Jinja.Data.Theory", b =>
                {
                    b.Navigation("ReferenceList");
                });
#pragma warning restore 612, 618
        }
    }
}
